name: "check"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  vet:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "`go vet`"
        run: |
          go vet ./...

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Run tests."
        run: |
          go test -v ./...
