name: "push"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "c032/gha-go@main"
